name: mkdocs

on:
  workflow_call:

permissions:
  contents: read

jobs:
  build-doc:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - shell: bash
        run: |
          echo "To be revised"
      - if: github.event_name == 'schedule'
        shell: bash
        run: |
          # mkdocs build --config-file mkdocs.yml --site-dir /html/gems_docs
          echo "To be revised"
